"""
@file TestCategories.py
@brief List of valid test categories for cilibc test runner.

This module defines ValidTestArguments, a list of supported test
categories and libraries that can be specified for building and
running tests with the cilibc test runner. The list includes both
high-level categories (such as "crt" or "sys") and specific library
modules (such as "stdio", "stdlib", "math", etc).

Used by scripts and test runners to validate and dispatch
test selections.
"""
from typing import List

#: List of valid test arguments/categories for the test runner.
ValidTestArguments: List[str] = [
    "all",
    # supertypes
    "crt",
    "sys",
    "arpa",
    "net",
    "netinet",
    # libs
    "aio",
    "arpa.inet",
    "assert",
    "complex",
    "cpio",
    "ctype",
    "devctl",
    "dirent",
    "dlfcn",
    "endian",
    "errno",
    "fcntl",
    "fenv",
    "float",
    "fmtmsg",
    "fnmatch",
    "ftw",
    "glob",
    "grp",
    "iconv",
    "inttypes",
    "iso646",
    "langinfo",
    "libintl",
    "libgen",
    "limits",
    "locale",
    "math",
    "monetary",
    "mqueue",
    "ndbm",
    "net.if",
    "netdb",
    "netinet.in",
    "netinet.tcp",
    "nl_types",
    "poll",
    "pthread",
    "pwd",
    "regex",
    "sched",
    "search",
    "semaphore",
    "setjmp",
    "signal",
    "spawn",
    "stdalign",
    "stdarg",
    "stdatomic",
    "stdbool",
    "stddef",
    "stdint",
    "stdio",
    "stdlib",
    "stdnoreturn",
    "string",
    "strings",
    "sys.ipc",
    "sys.mman",
    "sys.msg",
    "sys.resource",
    "sys.select",
    "sys.sem",
    "sys.shm",
    "sys.socket",
    "sys.stat",
    "sys.statvfs",
    "sys.time",
    "sys.times",
    "sys.types",
    "sys.uio",
    "sys.un",
    "sys.utsname",
    "sys.wait",
    "syslog",
    "tar",
    "termios",
    "tgmath",
    "threads",
    "time",
    "uchar",
    "unistd",
    "utmpx",
    "wchar",
    "wctype",
    "wordexp",
]
